name: Deploy Application
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: |
          cd /home/Git/Rabbit
          git reset --hard
          git pull
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd frontend
          npm ci
          npm run build
          lftp -e "mirror -R --delete ./build /; exit" -u ${{ secrets.sftp_username }},${{ secrets.sftp_password }} ${{ secrets.sftp_hostname }}
          systemctl restart rabbit-express.service
