name: Deploy Frontend
on:
  push:
    branches:
      - "main"

jobs:
  deploy-frontend:
    runs-on: self-hosted
    steps:
      - run: |
          cd /home/Git/Rabbit
          git reset --hard
          git pull
          cd frontend
          /root/.nvm/versions/node/v20.11.0/bin/npm ci
          /root/.nvm/versions/node/v20.11.0/bin/npm run build
          lftp sftp://${{ secrets.sftp_username }}:${{ secrets.sftp_password }}@${{ secrets.sftp_hostname }} -e "mirror --reverse ./build /; quit"
